# SPDX-License-Identifier: MIT
#
# This file may contain content generated or assisted by Artificial Intelligence
# tools and subsequently reviewed and modified by human contributors.
# See the LICENSE file for licensing terms and additional AI disclosures.

# ---------------------------------------------------------------------------
# Release automation. This repository has no build, so this Makefile exists for
# one purpose: to cut a release without anyone having to work out the next
# version number by hand.
#
# WHERE THE VERSION COMES FROM: the latest vX.Y.Z git tag. There is deliberately
# no VERSION file -- nothing here is built, so a VERSION file would be a second
# source of truth to keep in sync by hand, and release.yml validates the tag
# against CHANGELOG.md rather than against a file. Tags are the published state,
# so they are what a bump counts from.
#
# The bump targets stop at a LOCAL annotated tag. Pushing is a separate,
# explicit `release-push`, so a mistyped level or a bad changelog roll is
# recoverable with `git tag -d` + `git reset --hard HEAD~1` and never escapes
# the machine.
#
# Portability: no GNU coreutils on macOS. Bump arithmetic is POSIX `$$((...))`
# over parameter expansion, not `seq`/`bc`. The changelog is rewritten through
# `awk` into a temp file and `mv`d, never `sed -i` -- BSD `sed -i` demands a
# backup suffix and GNU `sed -i` refuses one, so no single `sed -i` invocation
# works on both this laptop and an ubuntu runner.
#
# Every awk program is kept on ONE physical line. A `\`-continuation inside a
# single-quoted awk program would be passed to the shell literally and awk
# would choke on it.
#
# Initial version generated by an AI assistant and reviewed/approved by
# Rubens Gomes.
#
# @author Rubens Gomes
# ---------------------------------------------------------------------------

.DEFAULT_GOAL := help

# Reporting only. The release recipes re-derive the current version in-shell
# AFTER fetching tags, because this `:=` is expanded at parse time and would
# otherwise report a stale value on a machine whose tags are behind.
CURRENT := $(shell git tag --list 'v[0-9]*.[0-9]*.[0-9]*' \
                     --sort=-v:refname 2>/dev/null | head -1 | sed 's/^v//')

# Preflight shared by every release target. Read-only: verifies the repo is in
# a fit state to be tagged and exits non-zero otherwise. Deliberately does NOT
# fail on untracked files -- `.idea/`-style noise is not a reason to block a
# release.
#
# Fetches tags with --force first: a local `v0` does not update on a plain
# fetch (git will not clobber an existing tag), and a stale tag list would make
# the bump count from the wrong number.
#
# Sets `_cur` for the callers below.
define RELEASE_PRECHECK
echo "=== RELEASE PRECHECK ==="; \
if [ ! -f CHANGELOG.md ]; then \
  echo "ERROR: CHANGELOG.md is missing at the repo root." >&2; exit 1; \
fi; \
if ! git diff --quiet || ! git diff --cached --quiet; then \
  echo "ERROR: working tree is dirty. Commit or stash before releasing." >&2; \
  git status --short >&2; \
  exit 1; \
fi; \
_br=$$(git rev-parse --abbrev-ref HEAD); \
if [ "$$_br" != "main" ]; then \
  echo "ERROR: releases are cut from main, not '$$_br'." >&2; \
  echo "  This repo is trunk-based: all work lands on main directly." >&2; \
  exit 1; \
fi; \
if git fetch --quiet --tags --force origin main 2>/dev/null; then \
  if ! git merge-base --is-ancestor FETCH_HEAD HEAD; then \
    echo "ERROR: HEAD does not contain origin/main." >&2; \
    echo "  Pull main before releasing." >&2; \
    exit 1; \
  fi; \
else \
  echo "  WARN: could not fetch origin, skipping the sync check"; \
fi; \
_cur=$$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname \
        | head -1 | sed 's/^v//'); \
if [ -z "$$_cur" ]; then _cur=0.0.0; fi; \
echo "  ok: current=v$$_cur, branch=$$_br, tree clean"
endef

# A bump with an empty [Unreleased] section produces a release note that says
# nothing, which is worse than no release at all. Counts `- ` bullets between
# the [Unreleased] heading and the next version heading.
#
# Anchoring on the full `^## \[` matters -- the prose at the top of CHANGELOG.md
# mentions `[Unreleased]` inline, and a looser pattern matches the prose.
define RELEASE_REQUIRE_UNRELEASED
_n=$$(awk '/^## \[Unreleased\]/{f=1;next} f && /^## \[[0-9]/{exit} f && /^- /{c++} END{print c+0}' CHANGELOG.md); \
if [ "$$_n" -eq 0 ]; then \
  echo "ERROR: CHANGELOG.md [Unreleased] has no entries - nothing to" \
       "release." >&2; \
  exit 1; \
fi; \
echo "  ok: $$_n changelog entrie(s) under [Unreleased]"
endef

# Creates the annotated tag for $$_new. Tag message is the bare tag, matching
# this repository's existing tags.
define RELEASE_TAG_BODY
_tag="v$$_new"; \
if git rev-parse -q --verify "refs/tags/$$_tag" >/dev/null; then \
  echo "ERROR: tag $$_tag already exists." >&2; exit 1; \
fi; \
git tag -a "$$_tag" -m "$$_tag"; \
echo "=== TAGGED $$_tag ==="; \
echo "  nothing has been pushed. Inspect with 'git show --stat HEAD', then:"; \
echo "    make release-push     publish $$_tag (fires release.yml)"; \
echo "  or undo with:"; \
echo "    git tag -d $$_tag && git reset --hard HEAD~1"
endef

# The bump itself. LEVEL (patch|minor|major) comes from the calling recipe.
# Order matters: every check that can fail runs BEFORE the first write, so a
# rejected release leaves the tree exactly as it found it.
#
# The changelog roll replaces the `## [Unreleased]` heading with a fresh empty
# [Unreleased] block followed by the new version heading. The old Unreleased
# body is left in place and therefore falls under the new version -- which is
# precisely the Keep a Changelog promotion.
define RELEASE_BUMP
$(RELEASE_PRECHECK); \
$(RELEASE_REQUIRE_UNRELEASED); \
_ma=$${_cur%%.*}; _rest=$${_cur#*.}; _mi=$${_rest%%.*}; _pa=$${_rest#*.}; \
case "$$LEVEL" in \
  major) _ma=$$((_ma + 1)); _mi=0; _pa=0;; \
  minor) _mi=$$((_mi + 1)); _pa=0;; \
  patch) _pa=$$((_pa + 1));; \
  *) echo "ERROR: unknown bump level '$$LEVEL'." >&2; exit 1;; \
esac; \
_new="$$_ma.$$_mi.$$_pa"; \
if git rev-parse -q --verify "refs/tags/v$$_new" >/dev/null; then \
  echo "ERROR: tag v$$_new already exists." >&2; exit 1; \
fi; \
if grep -q "^## \[$$_new\]" CHANGELOG.md; then \
  echo "ERROR: CHANGELOG.md already has a [$$_new] section." >&2; exit 1; \
fi; \
echo "=== RELEASE $$LEVEL: v$$_cur -> v$$_new ==="; \
awk -v ver="$$_new" -v day="$$(date +%F)" 'BEGIN{d=0} /^## \[Unreleased\]/ && !d {print; print ""; print "### Added"; print ""; print "### Changed"; print ""; print "### Fixed"; print ""; print "## [" ver "] - " day; d=1; next} {print}' CHANGELOG.md > CHANGELOG.md.tmp; \
mv CHANGELOG.md.tmp CHANGELOG.md; \
git add CHANGELOG.md; \
git commit -q -m "release: v$$_new"; \
$(RELEASE_TAG_BODY)
endef

.PHONY: help
help:
	@echo "Release:"
	@echo "  version           Show the current tag and what each bump" \
	      "would produce"
	@echo "  release-check     Preflight only. Changes nothing"
	@echo "  release-patch     Bump PATCH, roll changelog, commit, tag. Local only"
	@echo "  release-minor     Bump MINOR, roll changelog, commit, tag. Local only"
	@echo "  release-major     Bump MAJOR, roll changelog, commit, tag. Local only"
	@echo "  release-tag       Tag the changelog's top version without bumping"
	@echo "  release-push      Push main + the tag. Fires release.yml." \
	      "Not undoable"
	@echo ""
	@echo "See the Cutting a Release section in README.md for the" \
	      "full procedure."

.PHONY: version
version:
	@echo "Latest tag   : $(if $(CURRENT),v$(CURRENT),(none yet))"
	@echo "Changelog top: $$(awk '/^## \[[0-9]/{gsub(/^## \[/,""); gsub(/\].*/,""); print; exit}' CHANGELOG.md)"
	@_pub=$$(gh release view --json tagName -q .tagName 2>/dev/null \
	         || echo '(none)'); \
	 echo "Published    : $$_pub"

.PHONY: release-check
release-check:
	@$(RELEASE_PRECHECK); \
	 $(RELEASE_REQUIRE_UNRELEASED); \
	 _ma=$${_cur%%.*}; _rest=$${_cur#*.}; _mi=$${_rest%%.*}; _pa=$${_rest#*.}; \
	 echo ""; \
	 echo "  current        v$$_ma.$$_mi.$$_pa"; \
	 echo "  release-patch  v$$_ma.$$_mi.$$((_pa + 1))   docs and" \
	      "in-place tweaks no caller can observe"; \
	 echo "  release-minor  v$$_ma.$$((_mi + 1)).0   new workflows," \
	      "actions, or optional inputs"; \
	 echo "  release-major  v$$((_ma + 1)).0.0   anything that breaks a" \
	      "consumer stub"; \
	 echo ""; \
	 echo "  NOTE: a major bump also needs a prep commit repointing" \
	      "every internal"; \
	 echo "        'uses:' ref to the new major, or release.yml will" \
	      "reject the tag."

# The three bump targets. Each rolls the changelog, commits and tags -- all
# LOCALLY. `make release-push` is the separate, deliberate step that publishes.
.PHONY: release-patch
release-patch:
	@LEVEL=patch; $(RELEASE_BUMP)

.PHONY: release-minor
release-minor:
	@LEVEL=minor; $(RELEASE_BUMP)

.PHONY: release-major
release-major:
	@LEVEL=major; $(RELEASE_BUMP)

# Tag the version already at the top of the changelog, without bumping.
#
# An escape hatch, not part of the normal recipe: it only helps when a bump
# committed cleanly but the tag was lost before it was pushed.
.PHONY: release-tag
release-tag:
	@$(RELEASE_PRECHECK); \
	 _new=$$(awk '/^## \[[0-9]/{gsub(/^## \[/,""); gsub(/\].*/,""); print; exit}' CHANGELOG.md); \
	 if [ -z "$$_new" ]; then \
	   echo "ERROR: CHANGELOG.md has no version section." >&2; exit 1; \
	 fi; \
	 $(RELEASE_TAG_BODY)

# Publishes. The only release target that talks to the network, and the only
# one that is not undoable -- release.yml fires on the tag.
#
# `git push origin main` comes FIRST and is load-bearing. The release commit was
# made locally on main, so the branch must reach origin before the tag does --
# push the tag alone and release.yml fires against a commit nobody else can see.
# Both pushes go in one target so the ordering cannot be got wrong by hand.
.PHONY: release-push
release-push:
	@_new=$$(awk '/^## \[[0-9]/{gsub(/^## \[/,""); gsub(/\].*/,""); print; exit}' CHANGELOG.md); \
	 _tag="v$$_new"; \
	 if ! git rev-parse -q --verify "refs/tags/$$_tag" >/dev/null; then \
	   echo "ERROR: no local tag $$_tag. Run 'make release-<level>'" \
	        "first." >&2; exit 1; \
	 fi; \
	 echo "=== PUSH $$_tag ==="; \
	 git push origin main; \
	 git push origin "$$_tag"; \
	 echo "  pushed. Watch: gh run watch"
